/* Exercises a real isolated Strapi database. Never reads production credentials. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const appDir = path.join(root, 'strapi');
Object.assign(process.env, { ENV_PATH: path.join(appDir, '.tmp/styling-preview-archive/.env'), NODE_ENV: 'development', DATABASE_CLIENT: 'sqlite', DATABASE_FILENAME: '.tmp/styling-preview-archive/data.db', DATABASE_URL: '', HOST: '127.0.0.1', PORT: '1346', STRAPI_TELEMETRY_DISABLED: 'true', RESEND_API_KEY: '', SMTP_PASSWORD: '' });
process.chdir(appDir);
const { createStrapi, compileStrapi } = require(path.join(appDir, 'node_modules/@strapi/strapi'));
async function run() {
  const context = await compileStrapi({ appDir, ignoreDiagnostics: true });
  const app = createStrapi({ ...context, serveAdminPanel: false });
  await app.load();
  app.cron.destroy();
  const uid = 'api::styling-project.styling-project';
  const docs = app.documents(uid);
  const created = new Set();
  const passed = [];
  const ok = (name) => { passed.push(name); console.log(`PASS: ${name}`); };
  try {
    const original = await docs.findFirst({locale:'en',status:'published',filters:{slug:'wowy-grandma'},populate:{cover:true,gallery:{populate:{image:true}}}});
    const image1 = original.cover.id;
    const image2 = original.gallery.find(g=>g.image.id !== image1).image.id;
    const slug = `qa-readiness-${Date.now()}`;
    const data = {slug,title:'SAINT6 LOCAL QA',category:'Editorial',category_key:'editorial',summary:'English draft',body:'Local test content.',cover:image1,gallery:[{image:image1,alt:'First photograph'},{image:image2,alt:'Second photograph'}],credits:[{role:'Styling',name:'Trần Hoài Trang'}],seo_title:'Local QA',seo_description:'Local verification only.'};
    const draft = await docs.create({locale:'en',data});
    created.add(draft.documentId);
    const find = (locale='en') => docs.findOne({documentId:draft.documentId,locale,status:'published',populate:{cover:true,social_image:true,gallery:{populate:{image:true}}}});
    assert.equal(await find(),null);
    ok('Draft is hidden; source URL is optional');
    await docs.publish({documentId:draft.documentId,locale:'en'});
    assert.equal((await find()).summary,'English draft');
    await docs.update({documentId:draft.documentId,locale:'vi',data:{...data,title:'SAINT6 KIỂM THỬ',summary:'Nội dung tiếng Việt'}});
    assert.equal(await find('vi'),null);
    await docs.publish({documentId:draft.documentId,locale:'vi'});
    assert.equal((await find('vi')).summary,'Nội dung tiếng Việt');
    ok('English and Vietnamese share a URL and publish independently');
    await docs.update({documentId:draft.documentId,locale:'en',data:{summary:'English revision',cover:image2,social_image:image1,social_image_alt:'Sharing artwork',gallery:[{image:image2,alt:'Second first'},{image:image1,alt:'First second'}]}});
    assert.equal((await find()).summary,'English draft');
    await docs.publish({documentId:draft.documentId,locale:'en'});
    const updated = await find();
    assert.equal(updated.summary,'English revision');
    assert.equal(updated.cover.id,image2);
    assert.equal(updated.social_image.id,image1);
    assert.deepEqual(updated.gallery.map(g=>g.image.id),[image2,image1]);
    assert.equal((await find('vi')).summary,'Nội dung tiếng Việt');
    ok('Publish updates copy, cover, sharing image and gallery order without changing Vietnamese');
    await assert.rejects(docs.create({locale:'en',data}),/already uses this URL/);
    await assert.rejects(docs.update({documentId:draft.documentId,locale:'en',data:{slug:`${slug}-renamed`}}),/already been published/);
    await assert.rejects(docs.update({documentId:draft.documentId,locale:'en',data:{video_url:'https://youtube.com.evil.test/watch?v=12345678901'}}),/valid HTTPS YouTube/);
    await docs.update({documentId:draft.documentId,locale:'en',data:{video_url:'https://youtu.be/dQw4w9WgXcQ'}});
    ok('Duplicate URLs, published URL changes and invalid video hosts are rejected');
    const concurrent = await Promise.allSettled([1,2].map(()=>docs.create({locale:'en',data:{...data,slug:`${slug}-concurrent`}})));
    const winners = concurrent.filter(r=>r.status==='fulfilled');
    winners.forEach(r=>created.add(r.value.documentId));
    assert.equal(winners.length,1);
    assert.match(concurrent.find(r=>r.status==='rejected').reason.message,/already uses this URL/);
    ok('Concurrent duplicate creation saves only one document');
    await docs.unpublish({documentId:draft.documentId,locale:'en'});
    assert.equal(await find(),null);
    await assert.rejects(docs.update({documentId:draft.documentId,locale:'en',data:{slug:`${slug}-after-unpublish`}}),/already been published/);
    assert.ok(await find('vi'));
    ok('Unpublishing removes the locale while retaining the URL lock');
    const contact = await app.documents('api::shared-contact.shared-contact').findFirst({locale:'en',status:'published',populate:{image:true}});
    assert.ok(contact.heading && contact.text && contact.image && contact.form_title);
    const config = await app.plugin('content-manager').service('content-types').findConfiguration(app.contentType(uid));
    assert.match(config.metadatas.social_image.edit.description,/1200/);
    assert.equal(config.metadatas.locked_slug?.edit.visible,false);
    assert.equal(app.contentType('api::styling-page.styling-page').attributes.contact_text,undefined);
    ok('Shared contact media and copy, editor help and hidden URL lock are configured');
    const report = {date:new Date().toISOString(),environment:'isolated local SQLite',passed,cloudDatabaseTested:false};
    fs.writeFileSync(path.join(root,'output/styling-preview/cms-workflow-verification.json'),JSON.stringify(report,null,2)+'\n');
  } finally {
    for (const documentId of created) await docs.delete({documentId,locale:'*'});
    await app.destroy();
  }
}
run().catch(error=>{console.error(error);process.exitCode=1;});
